version: '3.8'

services:
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: myapp-server
    container_name: myapp-node-server
    command: npm start
    volumes:
      - ./backend/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    env_file: ./backend/.env
    # environment:
    #   - NODE_ENV=development
    networks:
      - app-network

  mongo: 
    image: mongo:6.0
    container_name: mongodb
    ports:
      - 27017:27017
    networks:
      - app-network
    volumes:
      - mongo-data:/data/db

  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: myapp-client
    container_name: myapp-react-client
    command: npm start
    volumes:
      - ./frontend/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - server
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
    app-network:
        driver: bridge

volumes:
    mongo-data:
      driver: local